# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_window.ui'
#
# Created: Thu Mar 17 17:01:56 2016
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayoutDown = QtGui.QVBoxLayout()
        self.verticalLayoutDown.setObjectName(_fromUtf8("verticalLayoutDown"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayoutTool = QtGui.QVBoxLayout()
        self.verticalLayoutTool.setObjectName(_fromUtf8("verticalLayoutTool"))
        self.pushButtonNarz0 = QtGui.QPushButton(self.centralwidget)
        self.pushButtonNarz0.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButtonNarz0.setMaximumSize(QtCore.QSize(32, 32))
        self.pushButtonNarz0.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconarchive/ikony/iconarchive/cursor.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonNarz0.setIcon(icon)
        self.pushButtonNarz0.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonNarz0.setCheckable(True)
        self.pushButtonNarz0.setChecked(True)
        self.pushButtonNarz0.setAutoExclusive(True)
        self.pushButtonNarz0.setObjectName(_fromUtf8("pushButtonNarz0"))
        self.verticalLayoutTool.addWidget(self.pushButtonNarz0)
        self.pushButtonNarz6 = QtGui.QPushButton(self.centralwidget)
        self.pushButtonNarz6.setEnabled(True)
        self.pushButtonNarz6.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButtonNarz6.setMaximumSize(QtCore.QSize(32, 32))
        self.pushButtonNarz6.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconarchive/ikony/iconarchive/select.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonNarz6.setIcon(icon1)
        self.pushButtonNarz6.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonNarz6.setCheckable(True)
        self.pushButtonNarz6.setChecked(False)
        self.pushButtonNarz6.setAutoExclusive(True)
        self.pushButtonNarz6.setObjectName(_fromUtf8("pushButtonNarz6"))
        self.verticalLayoutTool.addWidget(self.pushButtonNarz6)
        self.pushButtonNarz1 = QtGui.QPushButton(self.centralwidget)
        self.pushButtonNarz1.setEnabled(True)
        self.pushButtonNarz1.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButtonNarz1.setMaximumSize(QtCore.QSize(32, 32))
        self.pushButtonNarz1.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/qcad/ikony/qcad/Line2P.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonNarz1.setIcon(icon2)
        self.pushButtonNarz1.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonNarz1.setCheckable(True)
        self.pushButtonNarz1.setChecked(False)
        self.pushButtonNarz1.setAutoExclusive(True)
        self.pushButtonNarz1.setObjectName(_fromUtf8("pushButtonNarz1"))
        self.verticalLayoutTool.addWidget(self.pushButtonNarz1)
        self.pushButtonNarz2 = QtGui.QPushButton(self.centralwidget)
        self.pushButtonNarz2.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButtonNarz2.setMaximumSize(QtCore.QSize(32, 32))
        self.pushButtonNarz2.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/qcad/ikony/qcad/mLine2P.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonNarz2.setIcon(icon3)
        self.pushButtonNarz2.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonNarz2.setCheckable(True)
        self.pushButtonNarz2.setAutoExclusive(True)
        self.pushButtonNarz2.setObjectName(_fromUtf8("pushButtonNarz2"))
        self.verticalLayoutTool.addWidget(self.pushButtonNarz2)
        self.pushButtonNarz5 = QtGui.QPushButton(self.centralwidget)
        self.pushButtonNarz5.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButtonNarz5.setMaximumSize(QtCore.QSize(32, 32))
        self.pushButtonNarz5.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/qcad/ikony/qcad/LineAngle.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonNarz5.setIcon(icon4)
        self.pushButtonNarz5.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonNarz5.setCheckable(True)
        self.pushButtonNarz5.setAutoExclusive(True)
        self.pushButtonNarz5.setObjectName(_fromUtf8("pushButtonNarz5"))
        self.verticalLayoutTool.addWidget(self.pushButtonNarz5)
        self.pushButtonNarz3 = QtGui.QPushButton(self.centralwidget)
        self.pushButtonNarz3.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButtonNarz3.setMaximumSize(QtCore.QSize(32, 32))
        self.pushButtonNarz3.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/qcad/ikony/qcad/Arc3P.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonNarz3.setIcon(icon5)
        self.pushButtonNarz3.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonNarz3.setCheckable(True)
        self.pushButtonNarz3.setAutoExclusive(True)
        self.pushButtonNarz3.setObjectName(_fromUtf8("pushButtonNarz3"))
        self.verticalLayoutTool.addWidget(self.pushButtonNarz3)
        self.pushButtonNarz7 = QtGui.QPushButton(self.centralwidget)
        self.pushButtonNarz7.setEnabled(True)
        self.pushButtonNarz7.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButtonNarz7.setMaximumSize(QtCore.QSize(32, 32))
        self.pushButtonNarz7.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconarchive/ikony/iconarchive/arrow.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonNarz7.setIcon(icon6)
        self.pushButtonNarz7.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonNarz7.setCheckable(True)
        self.pushButtonNarz7.setChecked(False)
        self.pushButtonNarz7.setAutoExclusive(True)
        self.pushButtonNarz7.setObjectName(_fromUtf8("pushButtonNarz7"))
        self.verticalLayoutTool.addWidget(self.pushButtonNarz7)
        self.pushButtonNarz4 = QtGui.QPushButton(self.centralwidget)
        self.pushButtonNarz4.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButtonNarz4.setMaximumSize(QtCore.QSize(32, 32))
        self.pushButtonNarz4.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconarchive/ikony/iconarchive/sort.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonNarz4.setIcon(icon7)
        self.pushButtonNarz4.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonNarz4.setCheckable(True)
        self.pushButtonNarz4.setAutoExclusive(True)
        self.pushButtonNarz4.setObjectName(_fromUtf8("pushButtonNarz4"))
        self.verticalLayoutTool.addWidget(self.pushButtonNarz4)
        self.pushButtonNarz8 = QtGui.QPushButton(self.centralwidget)
        self.pushButtonNarz8.setEnabled(True)
        self.pushButtonNarz8.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButtonNarz8.setMaximumSize(QtCore.QSize(32, 32))
        self.pushButtonNarz8.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconarchive/ikony/iconarchive/catchp.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonNarz8.setIcon(icon8)
        self.pushButtonNarz8.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonNarz8.setCheckable(True)
        self.pushButtonNarz8.setChecked(False)
        self.pushButtonNarz8.setAutoExclusive(True)
        self.pushButtonNarz8.setObjectName(_fromUtf8("pushButtonNarz8"))
        self.verticalLayoutTool.addWidget(self.pushButtonNarz8)
        self.horizontalLayout.addLayout(self.verticalLayoutTool)
        self.verticalLayoutDown.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayoutDown, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_Plik = QtGui.QMenu(self.menubar)
        self.menu_Plik.setObjectName(_fromUtf8("menu_Plik"))
        self.menuWidok = QtGui.QMenu(self.menubar)
        self.menuWidok.setObjectName(_fromUtf8("menuWidok"))
        self.menuEdycja = QtGui.QMenu(self.menubar)
        self.menuEdycja.setObjectName(_fromUtf8("menuEdycja"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionNowy = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconarchive/ikony/iconarchive/new.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNowy.setIcon(icon9)
        self.actionNowy.setObjectName(_fromUtf8("actionNowy"))
        self.actionOtworz = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconarchive/ikony/iconarchive/open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOtworz.setIcon(icon10)
        self.actionOtworz.setObjectName(_fromUtf8("actionOtworz"))
        self.actionZapisz = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconarchive/ikony/iconarchive/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZapisz.setIcon(icon11)
        self.actionZapisz.setObjectName(_fromUtf8("actionZapisz"))
        self.actionZapisz_jako = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconarchive/ikony/iconarchive/saveas.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZapisz_jako.setIcon(icon12)
        self.actionZapisz_jako.setObjectName(_fromUtf8("actionZapisz_jako"))
        self.actionZakoncz = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconarchive/ikony/iconarchive/close.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZakoncz.setIcon(icon13)
        self.actionZakoncz.setObjectName(_fromUtf8("actionZakoncz"))
        self.actionStandardowy = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconarchive/ikony/iconarchive/ZoomNormal.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStandardowy.setIcon(icon14)
        self.actionStandardowy.setObjectName(_fromUtf8("actionStandardowy"))
        self.actionPowieksz = QtGui.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconarchive/ikony/iconarchive/ZoomIn.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPowieksz.setIcon(icon15)
        self.actionPowieksz.setObjectName(_fromUtf8("actionPowieksz"))
        self.actionPomniejsz = QtGui.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconarchive/ikony/iconarchive/ZoomOut.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPomniejsz.setIcon(icon16)
        self.actionPomniejsz.setObjectName(_fromUtf8("actionPomniejsz"))
        self.actionCofnij = QtGui.QAction(MainWindow)
        self.actionCofnij.setEnabled(False)
        self.actionCofnij.setVisible(True)
        self.actionCofnij.setObjectName(_fromUtf8("actionCofnij"))
        self.actionPonow = QtGui.QAction(MainWindow)
        self.actionPonow.setEnabled(False)
        self.actionPonow.setObjectName(_fromUtf8("actionPonow"))
        self.menu_Plik.addAction(self.actionNowy)
        self.menu_Plik.addAction(self.actionOtworz)
        self.menu_Plik.addSeparator()
        self.menu_Plik.addAction(self.actionZapisz)
        self.menu_Plik.addAction(self.actionZapisz_jako)
        self.menu_Plik.addSeparator()
        self.menu_Plik.addAction(self.actionZakoncz)
        self.menuWidok.addAction(self.actionStandardowy)
        self.menuWidok.addAction(self.actionPowieksz)
        self.menuWidok.addAction(self.actionPomniejsz)
        self.menuEdycja.addAction(self.actionCofnij)
        self.menuEdycja.addAction(self.actionPonow)
        self.menubar.addAction(self.menu_Plik.menuAction())
        self.menubar.addAction(self.menuEdycja.menuAction())
        self.menubar.addAction(self.menuWidok.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.menu_Plik.setTitle(_translate("MainWindow", "&Plik", None))
        self.menuWidok.setTitle(_translate("MainWindow", "Widok", None))
        self.menuEdycja.setTitle(_translate("MainWindow", "Edycja", None))
        self.actionNowy.setText(_translate("MainWindow", "Nowy", None))
        self.actionNowy.setShortcut(_translate("MainWindow", "Ctrl+N", None))
        self.actionOtworz.setText(_translate("MainWindow", "Otworz", None))
        self.actionOtworz.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionZapisz.setText(_translate("MainWindow", "Zapisz", None))
        self.actionZapisz.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionZapisz_jako.setText(_translate("MainWindow", "Zapisz jako", None))
        self.actionZapisz_jako.setShortcut(_translate("MainWindow", "Ctrl+Shift+S", None))
        self.actionZakoncz.setText(_translate("MainWindow", "Zakoncz", None))
        self.actionStandardowy.setText(_translate("MainWindow", "Standardowy", None))
        self.actionPowieksz.setText(_translate("MainWindow", "Powieksz", None))
        self.actionPowieksz.setShortcut(_translate("MainWindow", "Ctrl++", None))
        self.actionPomniejsz.setText(_translate("MainWindow", "Pomniejsz", None))
        self.actionPomniejsz.setShortcut(_translate("MainWindow", "Ctrl+-", None))
        self.actionCofnij.setText(_translate("MainWindow", "Cofnij", None))
        self.actionCofnij.setShortcut(_translate("MainWindow", "Ctrl+Z", None))
        self.actionPonow.setText(_translate("MainWindow", "Ponow", None))
        self.actionPonow.setShortcut(_translate("MainWindow", "Ctrl+Shift+Z", None))

import ikony_rc
